import { Signal } from '@/types/signals';

export const initialSignals: Signal[] = [
  {
    id: 'motor_voltage',
    name: 'Motor Voltage',
    value: null,
    unit: 'V',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 420, alarm: 450, direction: 'above' },
    icon: 'Zap',
  },
  {
    id: 'motor_current',
    name: 'Motor Current',
    value: null,
    unit: 'A',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 15, alarm: 20, direction: 'above' },
    icon: 'Activity',
  },
  {
    id: 'motor_power',
    name: 'Motor Power',
    value: null,
    unit: 'W',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 5000, alarm: 6000, direction: 'above' },
    icon: 'Gauge',
  },
  {
    id: 'motor_temp',
    name: 'Motor Winding Temp',
    value: null,
    unit: '°C',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 75, alarm: 90, direction: 'above' },
    icon: 'Thermometer',
  },
  {
    id: 'gearbox_temp',
    name: 'Gearbox Oil Temp',
    value: null,
    unit: '°C',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 70, alarm: 85, direction: 'above' },
    icon: 'Droplets',
  },
  {
    id: 'motor_vibration',
    name: 'Motor Vibration',
    value: null,
    unit: 'mm/s',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 4.5, alarm: 7.1, direction: 'above' },
    icon: 'Waves',
  },
  {
    id: 'gearbox_vibration',
    name: 'Gearbox Vibration',
    value: null,
    unit: 'mm/s',
    lastUpdate: null,
    status: 'offline',
    thresholds: { warning: 4.5, alarm: 7.1, direction: 'above' },
    icon: 'Radio',
  },
];

export const SIGNAL_TIMEOUT_MS = 30000; // Signal goes offline after 30s without update
export const HEARTBEAT_INTERVAL_MS = 5000; // Check connection every 5s
